version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "true"

phases:
  install:
    runtime-versions:
      terraform: 1.6
    commands:
      - echo "Installing Terraform"
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes"
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform changes"
      - terraform apply -auto-approve tfplan
