version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "true"
    TERRAFORM_VERSION: "1.6.0"
    STATE_BUCKET_PREFIX: "terraform-state-552516487395-test"  

phases:
  install:
    commands:
      - echo "Installing Terraform ${TERRAFORM_VERSION}"
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Getting AWS Account ID"
      - export STATE_BUCKET="${STATE_BUCKET_PREFIX}"
      - echo "Using state bucket ${STATE_BUCKET}"
      
      - cd infra/application
      
      # Criar backend.tf automaticamente
      - |
        cat > backend.tf <<EOF
        terraform {
          backend "s3" {
            bucket = "${STATE_BUCKET}"
            key    = "application/terraform.tfstate"
            region = "us-east-1"
          }
        }
        EOF
      
      - terraform init -reconfigure

  build:
    commands:
      - echo "Planning Terraform changes"
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform changes"
      - terraform apply -auto-approve tfplan