version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "true"
    TERRAFORM_VERSION: "1.6.0"

phases:
  install:
    commands:
      - echo "Installing Terraform ${TERRAFORM_VERSION}"
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - cd infra/application
      - terraform init -reconfigure

  build:
    commands:
      - echo "Planning Terraform changes"
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform changes"
      - terraform apply -auto-approve tfplan